
version: '3.8'
services:
  backend:
    build: ./backend
    container_name: stationery_backend
    volumes:
      - ./store_data:/app/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
  frontend:
    build: ./fr ontend
    container_name: stationery_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M